# Generated by Django 4.2.23 on 2025-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('posted_date', models.DateField()),
                ('job_url', models.URLField()),
            ],
        ),
    ]
