# Generated by Django 4.2.23 on 2025-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0002_alter_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
