# Generated by Django 4.2.23 on 2025-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0006_remove_job_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
