# Generated by Django 4.2.23 on 2025-09-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0007_job_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
