# Generated by Django 4.2.23 on 2025-09-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0008_alter_job_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='external_id',
            new_name='external_ids',
        ),
    ]
