# Generated by Django 4.2.23 on 2025-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0009_rename_external_id_job_external_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='external_ids',
        ),
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
