# Generated by Django 4.2.23 on 2025-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0010_remove_job_external_ids_job_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
