# Generated by Django 4.2.23 on 2025-09-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medjobs', '0011_alter_job_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='external_id',
        ),
    ]
